/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import { useGLTF } from "@react-three/drei";
import * as THREE from "three";
import { GLTF } from "three-stdlib";

type GLTFResult = GLTF & {
  nodes: {
    ["Mesh_body-top-case"]: THREE.Mesh;
    ["Mesh_grips-back"]: THREE.Mesh;
    ["Mesh_grips-front"]: THREE.Mesh;
    ["Mesh_internal-components"]: THREE.Mesh;
    Mesh_triggers: THREE.Mesh;
    ["Mesh_view-menu-share-buttons"]: THREE.Mesh;
    ["Mesh_bumpers-trans"]: THREE.Mesh;
    ["Mesh_back-switches"]: THREE.Mesh;
    ["Mesh_back-logo-decals"]: THREE.Mesh;
    ["Mesh_back-case-trans"]: THREE.Mesh;
    ["Mesh_abxy-buttons-trans"]: THREE.Mesh;
    ["Mesh_abxy-buttons-exterior-trans"]: THREE.Mesh;
    ["Mesh_lights-trans"]: THREE.Mesh;
    ["Mesh_thumbstick-bases"]: THREE.Mesh;
    ["Mesh_thumbstick-domes"]: THREE.Mesh;
    ["Mesh_thumbstick-rings"]: THREE.Mesh;
    ["Mesh_thumbstick-toppers"]: THREE.Mesh;
    ["Mesh_interposer-buttons"]: THREE.Mesh;
    ["Mesh_combined-noncustom"]: THREE.Mesh;
    ["Mesh_d-pad-faceted"]: THREE.Mesh;
    ["Mesh_d-pad-cross"]: THREE.Mesh;
    ["Mesh_d-pad-decals-alphad"]: THREE.Mesh;
  };
  materials: {
    Mt_default: THREE.MeshStandardMaterial;
  };
};

export function XboxEliteWirelessControllerSeries2(
  props: JSX.IntrinsicElements["group"]
) {
  const { nodes, materials } = useGLTF(
    "/models/XboxEliteWirelessControllerSeries2.glb"
  ) as GLTFResult;
  return (
    <group {...props} dispose={null}>
      <group name="Scene">
        <mesh
          name="Mesh_body-top-case"
          castShadow
          receiveShadow
          geometry={nodes["Mesh_body-top-case"].geometry}
          material={materials.Mt_default}
          userData={{ name: "Mesh_body-top-case" }}
        />
        <mesh
          name="Mesh_grips-back"
          castShadow
          receiveShadow
          geometry={nodes["Mesh_grips-back"].geometry}
          material={materials.Mt_default}
          userData={{ name: "Mesh_grips-back" }}
        />
        <mesh
          name="Mesh_grips-front"
          castShadow
          receiveShadow
          geometry={nodes["Mesh_grips-front"].geometry}
          material={materials.Mt_default}
          userData={{ name: "Mesh_grips-front" }}
        />
        <mesh
          name="Mesh_internal-components"
          castShadow
          receiveShadow
          geometry={nodes["Mesh_internal-components"].geometry}
          material={materials.Mt_default}
          userData={{ name: "Mesh_internal-components" }}
        />
        <mesh
          name="Mesh_triggers"
          castShadow
          receiveShadow
          geometry={nodes.Mesh_triggers.geometry}
          material={materials.Mt_default}
          userData={{ name: "Mesh_triggers" }}
        />
        <mesh
          name="Mesh_view-menu-share-buttons"
          castShadow
          receiveShadow
          geometry={nodes["Mesh_view-menu-share-buttons"].geometry}
          material={materials.Mt_default}
          userData={{ name: "Mesh_view-menu-share-buttons" }}
        />
        <mesh
          name="Mesh_bumpers-trans"
          castShadow
          receiveShadow
          geometry={nodes["Mesh_bumpers-trans"].geometry}
          material={materials.Mt_default}
          userData={{ name: "Mesh_bumpers-trans" }}
        />
        <mesh
          name="Mesh_back-switches"
          castShadow
          receiveShadow
          geometry={nodes["Mesh_back-switches"].geometry}
          material={materials.Mt_default}
          userData={{ name: "Mesh_back-switches" }}
        />
        <mesh
          name="Mesh_back-logo-decals"
          castShadow
          receiveShadow
          geometry={nodes["Mesh_back-logo-decals"].geometry}
          material={materials.Mt_default}
          userData={{ name: "Mesh_back-logo-decals" }}
        />
        <mesh
          name="Mesh_back-case-trans"
          castShadow
          receiveShadow
          geometry={nodes["Mesh_back-case-trans"].geometry}
          material={materials.Mt_default}
          userData={{ name: "Mesh_back-case-trans" }}
        />
        <mesh
          name="Mesh_abxy-buttons-trans"
          castShadow
          receiveShadow
          geometry={nodes["Mesh_abxy-buttons-trans"].geometry}
          material={materials.Mt_default}
          userData={{ name: "Mesh_abxy-buttons-trans" }}
        />
        <mesh
          name="Mesh_abxy-buttons-exterior-trans"
          castShadow
          receiveShadow
          geometry={nodes["Mesh_abxy-buttons-exterior-trans"].geometry}
          material={materials.Mt_default}
          userData={{ name: "Mesh_abxy-buttons-exterior-trans" }}
        />
        <mesh
          name="Mesh_lights-trans"
          castShadow
          receiveShadow
          geometry={nodes["Mesh_lights-trans"].geometry}
          material={materials.Mt_default}
          userData={{ name: "Mesh_lights-trans" }}
        />
        <mesh
          name="Mesh_thumbstick-bases"
          castShadow
          receiveShadow
          geometry={nodes["Mesh_thumbstick-bases"].geometry}
          material={materials.Mt_default}
          userData={{ name: "Mesh_thumbstick-bases" }}
        />
        <mesh
          name="Mesh_thumbstick-domes"
          castShadow
          receiveShadow
          geometry={nodes["Mesh_thumbstick-domes"].geometry}
          material={materials.Mt_default}
          userData={{ name: "Mesh_thumbstick-domes" }}
        />
        <mesh
          name="Mesh_thumbstick-rings"
          castShadow
          receiveShadow
          geometry={nodes["Mesh_thumbstick-rings"].geometry}
          material={materials.Mt_default}
          userData={{ name: "Mesh_thumbstick-rings" }}
        />
        <mesh
          name="Mesh_thumbstick-toppers"
          castShadow
          receiveShadow
          geometry={nodes["Mesh_thumbstick-toppers"].geometry}
          material={materials.Mt_default}
          userData={{ name: "Mesh_thumbstick-toppers" }}
        />
        <mesh
          name="Mesh_interposer-buttons"
          castShadow
          receiveShadow
          geometry={nodes["Mesh_interposer-buttons"].geometry}
          material={materials.Mt_default}
          userData={{ name: "Mesh_interposer-buttons" }}
        />
        <mesh
          name="Mesh_combined-noncustom"
          castShadow
          receiveShadow
          geometry={nodes["Mesh_combined-noncustom"].geometry}
          material={materials.Mt_default}
          userData={{ name: "Mesh_combined-noncustom" }}
        />
        <mesh
          name="Mesh_d-pad-faceted"
          castShadow
          receiveShadow
          geometry={nodes["Mesh_d-pad-faceted"].geometry}
          material={materials.Mt_default}
          userData={{ name: "Mesh_d-pad-faceted" }}
        />
        <mesh
          name="Mesh_d-pad-cross"
          castShadow
          receiveShadow
          geometry={nodes["Mesh_d-pad-cross"].geometry}
          material={materials.Mt_default}
          userData={{ name: "Mesh_d-pad-cross" }}
        />
        <mesh
          name="Mesh_d-pad-decals-alphad"
          castShadow
          receiveShadow
          geometry={nodes["Mesh_d-pad-decals-alphad"].geometry}
          material={materials.Mt_default}
          userData={{ name: "Mesh_d-pad-decals-alphad" }}
        />
      </group>
    </group>
  );
}

useGLTF.preload("/models/XboxEliteWirelessControllerSeries2.glb");
